services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Keeps data even if container stops

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://database:27017/rz2 # Connects via the service name 'database'
    env_file:
      - .env
    volumes:
      - ./backend:/app           # Syncs your local code to the container (Hot reload)
      - /app/node_modules        # Prevents local node_modules from overwriting container's
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"              # Change to 3000:3000 if using Create React App
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo_data: